const BRAND_PARKER = {
  "brand": "Parker",
  "brand_id": "parker",
  "type": "imported",
  "tagline": "The world's finest writing instruments",
  "wa": "919898298346",
  "collections": [
    {
      "id": "duofold",
      "name": "Duofold"
    },
    {
      "id": "ingenuity",
      "name": "Ingenuity"
    },
    {
      "id": "sonnet",
      "name": "Sonnet"
    },
    {
      "id": "parker51",
      "name": "Parker 51"
    },
    {
      "id": "im",
      "name": "Parker IM"
    },
    {
      "id": "ambient",
      "name": "Ambient"
    },
    {
      "id": "aster",
      "name": "Aster"
    },
    {
      "id": "odyssey",
      "name": "Odyssey"
    },
    {
      "id": "urban",
      "name": "Urban"
    },
    {
      "id": "fusion",
      "name": "Fusion"
    }
  ],
  "products": [
    {
      "id": "duofold-pioneers-gold",
      "name": "Duofold Pioneers Collection Gold Trim",
      "collection": "duofold",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Legendary Duofold fountain pen. Pioneers Collection. Gold Trim finish. Heritage craftsmanship.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_duofold_pioneers_gold"
    },
    {
      "id": "duofold-chevron-blue",
      "name": "Duofold Chevron Blue Gold Trim",
      "collection": "duofold",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Classic Duofold with Chevron pattern in Blue. Gold trim accents. Iconic fountain pen.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_duofold_chevron_blue"
    },
    {
      "id": "duofold-classic-black-gold",
      "name": "Duofold Classic Black Gold Trim",
      "collection": "duofold",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Timeless Duofold Classic in Black with Gold Trim. A fountain pen for connoisseurs.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_duofold_classic_black_gold"
    },
    {
      "id": "duofold-classic-black-chrome",
      "name": "Duofold Classic Black Chrome Trim",
      "collection": "duofold",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Classic Duofold in Black with Chrome Trim. Sleek and sophisticated writing instrument.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_duofold_classic_black_chrome"
    },
    {
      "id": "duofold-big-red-fp",
      "name": "Duofold Classic Big Red Vintage Chrome",
      "collection": "duofold",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Iconic Big Red Vintage Chrome Trim Duofold. Retro design with modern performance.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_duofold_big_red_fp"
    },
    {
      "id": "duofold-big-red-bp",
      "name": "Duofold Classic Big Red Vintage Chrome",
      "collection": "duofold",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Big Red Vintage Chrome Trim ballpoint. Pair with the fountain pen for a complete set.",
      "variants": "Ballpoint Pen | Price on request",
      "img_key": "parker_duofold_big_red_bp"
    },
    {
      "id": "ingenuity-arnold-palmer-fp",
      "name": "Ingenuity Arnold Palmer Signature Gold Trim",
      "collection": "ingenuity",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Exclusive Arnold Palmer Signature Edition. Handcrafted with gold trim. Be the author of your success.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_ingenuity_arnold_palmer_fp"
    },
    {
      "id": "ingenuity-arnold-palmer-rb",
      "name": "Ingenuity Arnold Palmer Signature Gold Trim",
      "collection": "ingenuity",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Arnold Palmer Signature Rollerball. Refined and modern aesthetic with signature arrow clip.",
      "variants": "Rollerball Pen | Price on request",
      "img_key": "parker_ingenuity_arnold_palmer_rb"
    },
    {
      "id": "ingenuity-pioneers-fp",
      "name": "Ingenuity Pioneers Collection Gold Trim",
      "collection": "ingenuity",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Pioneers Collection fountain pen. Commanding presence with robust large size. Intricately crafted.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_ingenuity_pioneers_fp"
    },
    {
      "id": "ingenuity-pioneers-rb",
      "name": "Ingenuity Pioneers Collection Gold Trim",
      "collection": "ingenuity",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Pioneers Collection rollerball. Modern aesthetic with signature arrow clip.",
      "variants": "Rollerball Pen | Price on request",
      "img_key": "parker_ingenuity_pioneers_rb"
    },
    {
      "id": "ingenuity-pioneers-bp",
      "name": "Ingenuity Pioneers Collection Gold Trim",
      "collection": "ingenuity",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Pioneers Collection ballpoint. Gold trim with sophisticated design language.",
      "variants": "Ballpoint Pen | Price on request",
      "img_key": "parker_ingenuity_pioneers_bp"
    },
    {
      "id": "sonnet-mt-fuji-fp",
      "name": "Sonnet Mt. Fuji Special Edition Pink Gold",
      "collection": "sonnet",
      "available": true,
      "badge": "Special Edition",
      "price_from": 55000,
      "description": "Exclusive Mt. Fuji Special Edition. Pink Gold Trim. A rare collector's fountain pen.",
      "variants": "Fountain Pen | MRP ₹55,000",
      "img_key": "parker_sonnet_mt_fuji_fp"
    },
    {
      "id": "sonnet-mt-fuji-rb",
      "name": "Sonnet Mt. Fuji Special Edition Pink Gold",
      "collection": "sonnet",
      "available": true,
      "badge": "Special Edition",
      "price_from": 35000,
      "description": "Mt. Fuji Special Edition Rollerball in Pink Gold Trim. Exceptional writing experience.",
      "variants": "Rollerball Pen | MRP ₹35,000",
      "img_key": "parker_sonnet_mt_fuji_rb"
    },
    {
      "id": "sonnet-mt-fuji-bp",
      "name": "Sonnet Mt. Fuji Special Edition Pink Gold",
      "collection": "sonnet",
      "available": true,
      "badge": "Special Edition",
      "price_from": 28500,
      "description": "Mt. Fuji Special Edition Ballpoint in Pink Gold Trim. Precision crafted.",
      "variants": "Ballpoint Pen | MRP ₹28,500",
      "img_key": "parker_sonnet_mt_fuji_bp"
    },
    {
      "id": "sonnet-pioneers-fp",
      "name": "Sonnet Pioneers Collection Gold Trim",
      "collection": "sonnet",
      "available": true,
      "badge": "New",
      "price_from": 45000,
      "description": "Pioneers Collection Sonnet fountain pen with Gold Trim. Exceptionally refined writing instrument.",
      "variants": "Fountain Pen | MRP ₹45,000",
      "img_key": "parker_sonnet_pioneers_fp"
    },
    {
      "id": "sonnet-pioneers-rb",
      "name": "Sonnet Pioneers Collection Gold Trim",
      "collection": "sonnet",
      "available": true,
      "badge": "New",
      "price_from": 25000,
      "description": "Pioneers Collection Sonnet rollerball. Beautifully crafted with premium materials.",
      "variants": "Rollerball Pen | MRP ₹25,000",
      "img_key": "parker_sonnet_pioneers_rb"
    },
    {
      "id": "sonnet-pioneers-bp",
      "name": "Sonnet Pioneers Collection Gold Trim",
      "collection": "sonnet",
      "available": true,
      "badge": "New",
      "price_from": 17000,
      "description": "Pioneers Collection Sonnet ballpoint. Elegant and precise writing tool.",
      "variants": "Ballpoint Pen | MRP ₹17,000",
      "img_key": "parker_sonnet_pioneers_bp"
    },
    {
      "id": "sonnet-metal-grey-rg",
      "name": "Sonnet Metal & Grey Lacquer Rose Gold",
      "collection": "sonnet",
      "available": true,
      "badge": "",
      "price_from": 28000,
      "description": "Metal & Grey Lacquer body with Rose Gold Trim. Sophisticated fusion fountain pen.",
      "variants": "Fountain Pen | MRP ₹28,000",
      "img_key": "parker_sonnet_metal_grey_rg"
    },
    {
      "id": "sonnet-metal-black-gold",
      "name": "Sonnet Metal & Black Lacquer Gold Trim",
      "collection": "sonnet",
      "available": true,
      "badge": "",
      "price_from": 26000,
      "description": "Metal & Black Lacquer with Gold Trim. Classic elegance in a premium fountain pen.",
      "variants": "Fountain Pen | MRP ₹26,000",
      "img_key": "parker_sonnet_metal_black_gold"
    },
    {
      "id": "sonnet-metal-blue-chrome",
      "name": "Sonnet Metal & Blue Lacquer Chrome",
      "collection": "sonnet",
      "available": true,
      "badge": "",
      "price_from": 26000,
      "description": "Metal & Blue Lacquer Chrome Trim fountain pen. Vibrant and distinguished.",
      "variants": "Fountain Pen | MRP ₹26,000",
      "img_key": "parker_sonnet_metal_blue_chrome"
    },
    {
      "id": "sonnet-metal-red-chrome",
      "name": "Sonnet Metal & Red Lacquer Chrome",
      "collection": "sonnet",
      "available": true,
      "badge": "",
      "price_from": 26000,
      "description": "Metal & Red Lacquer Chrome Trim fountain pen. Bold and elegant writing instrument.",
      "variants": "Fountain Pen | MRP ₹26,000",
      "img_key": "parker_sonnet_metal_red_chrome"
    },
    {
      "id": "sonnet-intense-red",
      "name": "Sonnet Intense Red Gold Trim",
      "collection": "sonnet",
      "available": true,
      "badge": "Bestseller",
      "price_from": 25000,
      "description": "Intensely vibrant red with Gold Trim. A stunning statement fountain pen.",
      "variants": "Fountain Pen | MRP ₹25,000",
      "img_key": "parker_sonnet_intense_red"
    },
    {
      "id": "parker51-deluxe-black-gold-fp",
      "name": "Parker 51 Deluxe Black Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "A classic reimagined. Streamlined silhouette with distinctive hooded nib. Deluxe Black Gold.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_51_deluxe_black_gold_fp"
    },
    {
      "id": "parker51-deluxe-black-gold-bp",
      "name": "Parker 51 Deluxe Black Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Deluxe Black Gold Trim ballpoint. Inspired by the world's most wanted pen.",
      "variants": "Ballpoint Pen | Price on request",
      "img_key": "parker_51_deluxe_black_gold_bp"
    },
    {
      "id": "parker51-deluxe-plum-gold-fp",
      "name": "Parker 51 Deluxe Plum Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Deluxe Plum with Gold Trim. Stunning bold colour in the iconic Parker 51 silhouette.",
      "variants": "Fountain Pen | Price on request",
      "img_key": "parker_51_deluxe_plum_gold_fp"
    },
    {
      "id": "parker51-deluxe-plum-gold-bp",
      "name": "Parker 51 Deluxe Plum Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "Premium",
      "price_from": null,
      "description": "Deluxe Plum Gold ballpoint. A bold and beautiful writing companion.",
      "variants": "Ballpoint Pen | Price on request",
      "img_key": "parker_51_deluxe_plum_gold_bp"
    },
    {
      "id": "parker51-black-gold-fp",
      "name": "Parker 51 Black Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "Bestseller",
      "price_from": 16500,
      "description": "The iconic Parker 51 in Black with Gold Trim. Retaining the world-famous hooded nib.",
      "variants": "Fountain Pen | MRP ₹16,500",
      "img_key": "parker_51_black_gold_fp"
    },
    {
      "id": "parker51-black-gold-bp",
      "name": "Parker 51 Black Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "Bestseller",
      "price_from": 11000,
      "description": "Parker 51 Black Gold ballpoint. Streamlined and stunning.",
      "variants": "Ballpoint Pen | MRP ₹11,000",
      "img_key": "parker_51_black_gold_bp"
    },
    {
      "id": "parker51-red-rage-gold-fp",
      "name": "Parker 51 Red Rage Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "New",
      "price_from": 16500,
      "description": "Bold Red Rage with Gold Trim. A vibrant take on the legendary Parker 51.",
      "variants": "Fountain Pen | MRP ₹16,500",
      "img_key": "parker_51_red_rage_gold_fp"
    },
    {
      "id": "parker51-red-rage-gold-bp",
      "name": "Parker 51 Red Rage Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "New",
      "price_from": 11000,
      "description": "Red Rage Gold ballpoint. Make a bold statement with every signature.",
      "variants": "Ballpoint Pen | MRP ₹11,000",
      "img_key": "parker_51_red_rage_gold_bp"
    },
    {
      "id": "parker51-forest-green-fp",
      "name": "Parker 51 Forest Green Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "New",
      "price_from": 16500,
      "description": "Forest Green with Gold Trim. Nature-inspired colour on an iconic silhouette.",
      "variants": "Fountain Pen | MRP ₹16,500",
      "img_key": "parker_51_forest_green_fp"
    },
    {
      "id": "parker51-forest-green-bp",
      "name": "Parker 51 Forest Green Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "New",
      "price_from": 11000,
      "description": "Forest Green Gold ballpoint. Elegant and distinctive.",
      "variants": "Ballpoint Pen | MRP ₹11,000",
      "img_key": "parker_51_forest_green_bp"
    },
    {
      "id": "parker51-turquoise-fp",
      "name": "Parker 51 Turquoise Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 15000,
      "description": "Vibrant Turquoise with Gold Trim. Retains the streamlined Parker 51 silhouette.",
      "variants": "Fountain Pen | MRP ₹15,000",
      "img_key": "parker_51_turquoise_fp"
    },
    {
      "id": "parker51-turquoise-bp",
      "name": "Parker 51 Turquoise Gold Trim",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 10500,
      "description": "Turquoise Gold Trim ballpoint. A jewel of a pen.",
      "variants": "Ballpoint Pen | MRP ₹10,500",
      "img_key": "parker_51_turquoise_bp"
    },
    {
      "id": "parker51-black-chrome-fp",
      "name": "Parker 51 Black Chrome Trim",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 8500,
      "description": "Parker 51 in Black with Chrome Trim. Classic and contemporary.",
      "variants": "Fountain Pen | MRP ₹8,500",
      "img_key": "parker_51_black_chrome_fp"
    },
    {
      "id": "parker51-black-chrome-bp",
      "name": "Parker 51 Black Chrome Trim",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 5800,
      "description": "Black Chrome Trim ballpoint. Sleek everyday writing companion.",
      "variants": "Ballpoint Pen | MRP ₹5,800",
      "img_key": "parker_51_black_chrome_bp"
    },
    {
      "id": "parker51-midnight-blue-fp",
      "name": "Parker 51 Midnight Blue Chrome",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 8500,
      "description": "Midnight Blue with Chrome Trim. Deep, rich colour on the iconic Parker 51.",
      "variants": "Fountain Pen | MRP ₹8,500",
      "img_key": "parker_51_midnight_blue_fp"
    },
    {
      "id": "parker51-burgundy-fp",
      "name": "Parker 51 Burgundy Chrome Trim",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 8500,
      "description": "Rich Burgundy with Chrome Trim. A sophisticated and timeless writing instrument.",
      "variants": "Fountain Pen | MRP ₹8,500",
      "img_key": "parker_51_burgundy_fp"
    },
    {
      "id": "parker51-teal-fp",
      "name": "Parker 51 Teal Blue Chrome Trim",
      "collection": "parker51",
      "available": true,
      "badge": "",
      "price_from": 8500,
      "description": "Beautiful Teal Blue with Chrome Trim. Distinctive and vibrant.",
      "variants": "Fountain Pen | MRP ₹8,500",
      "img_key": "parker_51_teal_fp"
    },
    {
      "id": "im-pioneers-fp",
      "name": "Parker IM Pioneers Collection Gold Trim",
      "collection": "im",
      "available": true,
      "badge": "New",
      "price_from": 9500,
      "description": "IM Pioneers Collection fountain pen with stunning Gold Trim. Premium everyday writing.",
      "variants": "Fountain Pen | MRP ₹9,500",
      "img_key": "parker_im_pioneers_fp"
    },
    {
      "id": "im-pioneers-rb",
      "name": "Parker IM Pioneers Collection Gold Trim",
      "collection": "im",
      "available": true,
      "badge": "New",
      "price_from": 8000,
      "description": "IM Pioneers Collection rollerball. Smooth and reliable everyday writer.",
      "variants": "Rollerball Pen | MRP ₹8,000",
      "img_key": "parker_im_pioneers_rb"
    },
    {
      "id": "im-pioneers-bp",
      "name": "Parker IM Pioneers Collection Gold Trim",
      "collection": "im",
      "available": true,
      "badge": "New",
      "price_from": 5500,
      "description": "IM Pioneers Collection ballpoint. A modern everyday workhorse.",
      "variants": "Ballpoint Pen | MRP ₹5,500",
      "img_key": "parker_im_pioneers_bp"
    },
    {
      "id": "im-rituals-green-fp",
      "name": "Parker IM Rituals Green Gold Trim",
      "collection": "im",
      "available": true,
      "badge": "New",
      "price_from": 6500,
      "description": "Rituals Green with Gold Trim fountain pen. Fresh and sophisticated.",
      "variants": "Fountain Pen | MRP ₹6,500",
      "img_key": "parker_im_rituals_green_fp"
    },
    {
      "id": "im-rituals-green-rb",
      "name": "Parker IM Rituals Green Gold Trim",
      "collection": "im",
      "available": true,
      "badge": "New",
      "price_from": 6000,
      "description": "Rituals Green rollerball. Distinctive colour for a distinctive writer.",
      "variants": "Rollerball Pen | MRP ₹6,000",
      "img_key": "parker_im_rituals_green_rb"
    },
    {
      "id": "im-rituals-green-bp",
      "name": "Parker IM Rituals Green Gold Trim",
      "collection": "im",
      "available": true,
      "badge": "New",
      "price_from": 5000,
      "description": "Rituals Green ballpoint. A fresh take on the classic IM.",
      "variants": "Ballpoint Pen | MRP ₹5,000",
      "img_key": "parker_im_rituals_green_bp"
    },
    {
      "id": "im-monochrome-blue-fp",
      "name": "Parker IM Monochrome Blue Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 6200,
      "description": "Full Monochrome Blue — body and trim in matching blue. Bold and unified.",
      "variants": "Fountain Pen | MRP ₹6,200",
      "img_key": "parker_im_monochrome_blue_fp"
    },
    {
      "id": "im-monochrome-blue-rb",
      "name": "Parker IM Monochrome Blue Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 5800,
      "description": "Monochrome Blue rollerball. Striking all-blue statement piece.",
      "variants": "Rollerball Pen | MRP ₹5,800",
      "img_key": "parker_im_monochrome_blue_rb"
    },
    {
      "id": "im-monochrome-blue-bp",
      "name": "Parker IM Monochrome Blue Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 4100,
      "description": "Monochrome Blue ballpoint. Modern and distinctive.",
      "variants": "Ballpoint Pen | MRP ₹4,100",
      "img_key": "parker_im_monochrome_blue_bp"
    },
    {
      "id": "im-monochrome-burgundy-fp",
      "name": "Parker IM Monochrome Burgundy Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 5900,
      "description": "All-Burgundy Monochrome fountain pen. Deep, rich and sophisticated.",
      "variants": "Fountain Pen | MRP ₹5,900",
      "img_key": "parker_im_monochrome_burgundy_fp"
    },
    {
      "id": "im-monochrome-titanium-fp",
      "name": "Parker IM Monochrome Titanium Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 5900,
      "description": "Monochrome Titanium fountain pen. Industrial-chic all-grey aesthetic.",
      "variants": "Fountain Pen | MRP ₹5,900",
      "img_key": "parker_im_monochrome_titanium_fp"
    },
    {
      "id": "im-monochrome-champagne-fp",
      "name": "Parker IM Monochrome Champagne Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 5100,
      "description": "Monochrome Champagne fountain pen. Soft golden tones with refined monochrome design.",
      "variants": "Fountain Pen | MRP ₹5,100",
      "img_key": "parker_im_monochrome_champagne_fp"
    },
    {
      "id": "im-professional-marine-fp",
      "name": "Parker IM Professional Marine Blue Black",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 4100,
      "description": "Professional Marine Blue on Black body. Smart and modern writing instrument.",
      "variants": "Fountain Pen | MRP ₹4,100",
      "img_key": "parker_im_professional_marine_fp"
    },
    {
      "id": "im-professional-marine-rb",
      "name": "Parker IM Professional Marine Blue Black",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 3300,
      "description": "Marine Blue Black rollerball. Everyday professional writing tool.",
      "variants": "Rollerball Pen | MRP ₹3,300",
      "img_key": "parker_im_professional_marine_rb"
    },
    {
      "id": "im-professional-marine-bp",
      "name": "Parker IM Professional Marine Blue Black",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 2800,
      "description": "Marine Blue Black ballpoint. Reliable daily writer.",
      "variants": "Ballpoint Pen | MRP ₹2,800",
      "img_key": "parker_im_professional_marine_bp"
    },
    {
      "id": "im-professional-flame-fp",
      "name": "Parker IM Professional Flame Orange Black",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 4100,
      "description": "Flame Orange on Black body. Bold accent for the confident professional.",
      "variants": "Fountain Pen | MRP ₹4,100",
      "img_key": "parker_im_professional_flame_fp"
    },
    {
      "id": "im-professional-amethyst-fp",
      "name": "Parker IM Professional Amethyst Purple Black",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 4100,
      "description": "Amethyst Purple on Black. Distinctive colour for creative professionals.",
      "variants": "Fountain Pen | MRP ₹4,100",
      "img_key": "parker_im_professional_amethyst_fp"
    },
    {
      "id": "im-black-chrome-fp",
      "name": "Parker IM Black Chrome Trim",
      "collection": "im",
      "available": true,
      "badge": "Bestseller",
      "price_from": 2800,
      "description": "Classic IM in Black with Chrome Trim. The go-to pen for everyday elegance.",
      "variants": "Fountain Pen | MRP ₹2,800",
      "img_key": "parker_im_black_chrome_fp"
    },
    {
      "id": "im-black-chrome-rb",
      "name": "Parker IM Black Chrome Trim",
      "collection": "im",
      "available": true,
      "badge": "Bestseller",
      "price_from": 2500,
      "description": "IM Black Chrome rollerball. Smooth and dependable.",
      "variants": "Rollerball Pen | MRP ₹2,500",
      "img_key": "parker_im_black_chrome_rb"
    },
    {
      "id": "im-black-chrome-bp",
      "name": "Parker IM Black Chrome Trim",
      "collection": "im",
      "available": true,
      "badge": "Bestseller",
      "price_from": 2300,
      "description": "IM Black Chrome ballpoint. The classic everyday writer.",
      "variants": "Ballpoint Pen | MRP ₹2,300",
      "img_key": "parker_im_black_chrome_bp"
    },
    {
      "id": "im-white-chrome-fp",
      "name": "Parker IM White Chrome Trim",
      "collection": "im",
      "available": true,
      "badge": "",
      "price_from": 2700,
      "description": "Crisp White with Chrome Trim. Clean and contemporary fountain pen.",
      "variants": "Fountain Pen | MRP ₹2,700",
      "img_key": "parker_im_white_chrome_fp"
    },
    {
      "id": "ambient-deluxe-black-gold-fp",
      "name": "Ambient Deluxe Black Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "",
      "price_from": 4000,
      "description": "Ambient Deluxe with lacquered/electroplated body. Quadruplet vertical lines. Premium fountain pen.",
      "variants": "Fountain Pen | MRP ₹4,000",
      "img_key": "parker_ambient_deluxe_black_gold_fp"
    },
    {
      "id": "ambient-deluxe-black-gold-rb",
      "name": "Ambient Deluxe Black Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "",
      "price_from": 3600,
      "description": "Ambient Deluxe rollerball. High-performance functionality with great grip.",
      "variants": "Rollerball Pen | MRP ₹3,600",
      "img_key": "parker_ambient_deluxe_black_gold_rb"
    },
    {
      "id": "ambient-deluxe-black-gold-bp",
      "name": "Ambient Deluxe Black Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "",
      "price_from": 3300,
      "description": "Ambient Deluxe ballpoint. Pristine, classy and reliable.",
      "variants": "Ballpoint Pen | MRP ₹3,300",
      "img_key": "parker_ambient_deluxe_black_gold_bp"
    },
    {
      "id": "ambient-lacque-black-gold-fp",
      "name": "Ambient Lacque Black Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "Bestseller",
      "price_from": 3400,
      "description": "Lacquered Black body with Gold Trim. Timeless appeal with smooth writing experience.",
      "variants": "Fountain Pen | MRP ₹3,400",
      "img_key": "parker_ambient_lacque_black_gold_fp"
    },
    {
      "id": "ambient-lacque-black-gold-rb",
      "name": "Ambient Lacque Black Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "Bestseller",
      "price_from": 3100,
      "description": "Ambient Lacque Black Gold rollerball. Smooth ceramic roller for flawless writing.",
      "variants": "Rollerball Pen | MRP ₹3,100",
      "img_key": "parker_ambient_lacque_black_gold_rb"
    },
    {
      "id": "ambient-lacque-black-gold-bp",
      "name": "Ambient Lacque Black Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "Bestseller",
      "price_from": 2900,
      "description": "Classic Black Gold ballpoint. Exudes a charm best captivated when you hold it.",
      "variants": "Ballpoint Pen | MRP ₹2,900",
      "img_key": "parker_ambient_lacque_black_gold_bp"
    },
    {
      "id": "ambient-blue-gold-rb",
      "name": "Ambient Blue Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "",
      "price_from": 3200,
      "description": "Ambient in Blue with Gold Trim rollerball. Vibrant and distinguished.",
      "variants": "Rollerball Pen | MRP ₹3,200",
      "img_key": "parker_ambient_blue_gold_rb"
    },
    {
      "id": "ambient-blue-gold-bp",
      "name": "Ambient Blue Gold Trim",
      "collection": "ambient",
      "available": true,
      "badge": "",
      "price_from": 2900,
      "description": "Ambient Blue Gold ballpoint. A refined everyday companion.",
      "variants": "Ballpoint Pen | MRP ₹2,900",
      "img_key": "parker_ambient_blue_gold_bp"
    },
    {
      "id": "urban-muted-black-gold-bp",
      "name": "Urban Muted Black Gold Trim",
      "collection": "urban",
      "available": true,
      "badge": "",
      "price_from": 3000,
      "description": "Eye-catching Urban with muted black and gold. Curved design with remarkable performance.",
      "variants": "Ballpoint Pen | MRP ₹3,000",
      "img_key": "parker_urban_muted_black_gold_bp"
    },
    {
      "id": "urban-muted-black-chrome-bp",
      "name": "Urban Muted Black Chrome Trim",
      "collection": "urban",
      "available": true,
      "badge": "",
      "price_from": 2700,
      "description": "Urban Muted Black with Chrome. Over a century of Parker tradition in dynamic design.",
      "variants": "Ballpoint Pen | MRP ₹2,700",
      "img_key": "parker_urban_muted_black_chrome_bp"
    },
    {
      "id": "urban-metro-metallic-chrome-bp",
      "name": "Urban Metro Metallic Chrome Trim",
      "collection": "urban",
      "available": true,
      "badge": "",
      "price_from": 2700,
      "description": "Metro Metallic Chrome Urban. Full metallic body with chrome trim for a premium feel.",
      "variants": "Ballpoint Pen | MRP ₹2,700",
      "img_key": "parker_urban_metro_metallic_chrome_bp"
    },
    {
      "id": "aster-essential-black-gold-fp",
      "name": "Aster Essential Black & Gold",
      "collection": "aster",
      "available": true,
      "badge": "",
      "price_from": 2700,
      "description": "Contemporary and unique body design. Blended with classy Gold Trim. Parker Aster fountain pen.",
      "variants": "Fountain Pen | MRP ₹2,700",
      "img_key": "parker_aster_essential_black_gold_fp"
    },
    {
      "id": "aster-essential-black-gold-rb",
      "name": "Aster Essential Black & Gold",
      "collection": "aster",
      "available": true,
      "badge": "",
      "price_from": 2400,
      "description": "Aster Essential rollerball with Black & Gold styling. Smooth and elegant.",
      "variants": "Rollerball Pen | MRP ₹2,400",
      "img_key": "parker_aster_essential_black_gold_rb"
    },
    {
      "id": "aster-essential-black-gold-bp",
      "name": "Aster Essential Black & Gold",
      "collection": "aster",
      "available": true,
      "badge": "",
      "price_from": 2200,
      "description": "Aster Essential ballpoint. Personality-suiting classy style.",
      "variants": "Ballpoint Pen | MRP ₹2,200",
      "img_key": "parker_aster_essential_black_gold_bp"
    },
    {
      "id": "aster-brushed-metal-gold-fp",
      "name": "Aster Brushed Metal Gold Trim",
      "collection": "aster",
      "available": true,
      "badge": "Bestseller",
      "price_from": 2100,
      "description": "Brushed Metal body with Gold Trim. Clean, minimalist design for professionals.",
      "variants": "Fountain Pen | MRP ₹2,100",
      "img_key": "parker_aster_brushed_metal_gold_fp"
    },
    {
      "id": "aster-brushed-metal-gold-rb",
      "name": "Aster Brushed Metal Gold Trim",
      "collection": "aster",
      "available": true,
      "badge": "Bestseller",
      "price_from": 1850,
      "description": "Brushed Metal Gold rollerball. Reliable and stylish everyday writer.",
      "variants": "Rollerball Pen | MRP ₹1,850",
      "img_key": "parker_aster_brushed_metal_gold_rb"
    },
    {
      "id": "aster-brushed-metal-gold-bp",
      "name": "Aster Brushed Metal Gold Trim",
      "collection": "aster",
      "available": true,
      "badge": "Bestseller",
      "price_from": 1650,
      "description": "Brushed Metal Gold ballpoint. The ideal corporate gift pen.",
      "variants": "Ballpoint Pen | MRP ₹1,650",
      "img_key": "parker_aster_brushed_metal_gold_bp"
    },
    {
      "id": "aster-lacque-black-gold-fp",
      "name": "Aster Lacque Black Gold Trim",
      "collection": "aster",
      "available": true,
      "badge": "",
      "price_from": 2000,
      "description": "Lacquered Black with Gold Trim fountain pen. Timeless and professional.",
      "variants": "Fountain Pen | MRP ₹2,000",
      "img_key": "parker_aster_lacque_black_gold_fp"
    },
    {
      "id": "aster-matte-black-gold-fp",
      "name": "Aster Matte Black Gold Trim",
      "collection": "aster",
      "available": true,
      "badge": "",
      "price_from": 2000,
      "description": "Matte Black with Gold Trim. Bold and understated fountain pen.",
      "variants": "Fountain Pen | MRP ₹2,000",
      "img_key": "parker_aster_matte_black_gold_fp"
    },
    {
      "id": "aster-matte-blue-gold-fp",
      "name": "Aster Matte Blue Gold Trim",
      "collection": "aster",
      "available": true,
      "badge": "",
      "price_from": 1900,
      "description": "Matte Blue with Gold Trim. Rich blue tones for a distinguished look.",
      "variants": "Fountain Pen | MRP ₹1,900",
      "img_key": "parker_aster_matte_blue_gold_fp"
    },
    {
      "id": "odyssey-gold-fp",
      "name": "Odyssey Gold – Gold Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "",
      "price_from": 4100,
      "description": "All-gold Odyssey fountain pen. Premium metal body with gold trim. Truly opulent.",
      "variants": "Fountain Pen | MRP ₹4,100",
      "img_key": "parker_odyssey_gold_fp"
    },
    {
      "id": "odyssey-gold-rb",
      "name": "Odyssey Gold – Gold Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "",
      "price_from": 3600,
      "description": "All-gold Odyssey rollerball. Smooth, prestigious writing instrument.",
      "variants": "Rollerball Pen | MRP ₹3,600",
      "img_key": "parker_odyssey_gold_rb"
    },
    {
      "id": "odyssey-gold-bp",
      "name": "Odyssey Gold – Gold Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "",
      "price_from": 3100,
      "description": "All-gold Odyssey ballpoint. Make a statement in every meeting.",
      "variants": "Ballpoint Pen | MRP ₹3,100",
      "img_key": "parker_odyssey_gold_bp"
    },
    {
      "id": "odyssey-brushed-gold-fp",
      "name": "Odyssey Brushed Metal Gold Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "Bestseller",
      "price_from": 3100,
      "description": "Brushed Metal with Gold Trim fountain pen. Reliable premium writing.",
      "variants": "Fountain Pen | MRP ₹3,100",
      "img_key": "parker_odyssey_brushed_gold_fp"
    },
    {
      "id": "odyssey-brushed-gold-rb",
      "name": "Odyssey Brushed Metal Gold Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "Bestseller",
      "price_from": 2800,
      "description": "Brushed Metal Gold rollerball. Everyday premium quality.",
      "variants": "Rollerball Pen | MRP ₹2,800",
      "img_key": "parker_odyssey_brushed_gold_bp"
    },
    {
      "id": "odyssey-brushed-chrome-fp",
      "name": "Odyssey Brushed Metal Chrome Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "",
      "price_from": 2850,
      "description": "Brushed Metal with Chrome Trim fountain pen. Clean and professional.",
      "variants": "Fountain Pen | MRP ₹2,850",
      "img_key": "parker_odyssey_brushed_chrome_fp"
    },
    {
      "id": "odyssey-lacque-black-gold-fp",
      "name": "Odyssey Lacque Black Gold Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "",
      "price_from": 2800,
      "description": "Lacquered Black with Gold Trim. Classic elegance in the Odyssey range.",
      "variants": "Fountain Pen | MRP ₹2,800",
      "img_key": "parker_odyssey_lacque_black_gold_fp"
    },
    {
      "id": "odyssey-lacque-black-chrome-fp",
      "name": "Odyssey Lacque Black Chrome Trim",
      "collection": "odyssey",
      "available": true,
      "badge": "",
      "price_from": 2550,
      "description": "Lacquered Black with Chrome Trim. Sleek professional fountain pen.",
      "variants": "Fountain Pen | MRP ₹2,550",
      "img_key": "parker_odyssey_lacque_black_chrome_fp"
    },
    {
      "id": "fusion-matte-black-gold-bp",
      "name": "Fusion Matte Black Gold Trim",
      "collection": "fusion",
      "available": true,
      "badge": "",
      "price_from": 1200,
      "description": "Parker Fusion in Matte Black with Gold Trim. Entry-level elegance.",
      "variants": "Ballpoint Pen | MRP ₹1,200",
      "img_key": "parker_fusion_matte_black_gold_bp"
    },
    {
      "id": "fusion-matte-black-chrome-bp",
      "name": "Fusion Matte Black Chrome Trim",
      "collection": "fusion",
      "available": true,
      "badge": "",
      "price_from": 1100,
      "description": "Fusion Matte Black with Chrome Trim. Smart everyday ballpoint.",
      "variants": "Ballpoint Pen | MRP ₹1,100",
      "img_key": "parker_fusion_matte_black_chrome_bp"
    },
    {
      "id": "fusion-shiny-chrome-gold-bp",
      "name": "Fusion Shiny Chrome Gold Trim",
      "collection": "fusion",
      "available": true,
      "badge": "",
      "price_from": 1200,
      "description": "Shiny Chrome with Gold Trim. All-metal premium ballpoint at an accessible price.",
      "variants": "Ballpoint Pen | MRP ₹1,200",
      "img_key": "parker_fusion_shiny_chrome_gold_bp"
    },
    {
      "id": "fusion-lacque-black-gold-bp",
      "name": "Fusion Lacque Black Gold Trim",
      "collection": "fusion",
      "available": true,
      "badge": "Bestseller",
      "price_from": 1200,
      "description": "Lacquered Black with Gold Trim. Elegant entry to the Parker family.",
      "variants": "Ballpoint Pen | MRP ₹1,200",
      "img_key": "parker_fusion_lacque_black_gold_bp"
    },
    {
      "id": "fusion-lacque-black-chrome-bp",
      "name": "Fusion Lacque Black Chrome Trim",
      "collection": "fusion",
      "available": true,
      "badge": "",
      "price_from": 1100,
      "description": "Lacquered Black Chrome ballpoint. A refined pen for everyday use.",
      "variants": "Ballpoint Pen | MRP ₹1,100",
      "img_key": "parker_fusion_lacque_black_chrome_bp"
    }
  ]
};
